### ISSUE TITLE
Akzente

### ISSUE THREAD

**Issue by 37Komma5** [SpotlightForBugs/Wortraetsel#34]
Wrong repository! Use [@SpotlightForBugs/wortraetselWeb](https://github.com/SpotlightForBugs/wortraetselWeb) instead

**Comment by SpotlightForBugs** [comment]
@37Komma5 welches Wort war es?

**Comment by SpotlightForBugs** [comment]
@37Komma5

**Comment by SpotlightForBugs** [comment]
Leider hast du das falsche repository erwischt. 
https://github.com/SpotlightForBugs/wortraetselWeb Für die Website
